### ISSUE TITLE
cucumber cpp gives error:   no implicit conversion of nil into String (TypeError)

### ISSUE THREAD

**Issue by ozenozkaya** [cucumber/cucumber-cpp#194]
## Summary
Calculator example gives "no implicit conversion of nil into String error. I changed nothing and cloned latest version of the repo. I am building the cucumber-cpp in Ubuntu 16.04 64-bit version.

Logs:

+ build/examples/Calc/GTestCalculatorSteps
+ cucumber examples/Calc
Feature: Addition
  In order to avoid silly mistakes
  As a math idiot 
  I want to be told the sum of two numbers

  Scenario Outline: Add two numbers                    # examples/Calc/features/addition.feature:7
    Given I have entered <input_1> into the calculator # examples/Calc/features/addition.feature:8
    And I have entered <input_2> into the calculator   # examples/Calc/features/addition.feature:9
    When I press <button>                              # examples/Calc/features/addition.feature:10
    Then the result should be <output> on the screen   # examples/Calc/features/addition.feature:11

    Examples: 
      | input_1 | input_2 | button | output |
      no implicit conversion of nil into String (TypeError)
      ./features/support/hooks.rb:4:in `exists?'
      ./features/support/hooks.rb:4:in `Before'
      | 20      | 30      | add    | 50     |
      no implicit conversion of nil into String (TypeError)
      ./features/support/hooks.rb:4:in `exists?'
      ./features/support/hooks.rb:4:in `Before'
      | 2       | 5       | add    | 7      |
      no implicit conversion of nil into String (TypeError)
      ./features/support/hooks.rb:4:in `exists?'
      ./features/support/hooks.rb:4:in `Before'
      | 0       | 40      | add    | 40     |

Feature: Division
  In order to avoid silly mistakes
  Cashiers must be able to calculate a fraction

  Scenario: Regular numbers                     # examples/Calc/features/division.feature:6
  no implicit conversion of nil into String (TypeError)
  ./features/support/hooks.rb:4:in `exists?'
  ./features/support/hooks.rb:4:in `Before'
    Given I have entered 3 into the calculator  # examples/Calc/features/division.feature:7
    And I have entered 2 into the calculator    # examples/Calc/features/division.feature:8
    When I press divide                         # examples/Calc/features/division.feature:9
    Then the result should be 1.5 on the screen # examples/Calc/features/division.feature:10

Failing Scenarios:
cucumber examples/Calc/features/addition.feature:15 # Scenario Outline: Add two numbers, Examples (#1)
cucumber examples/Calc/features/addition.feature:16 # Scenario Outline: Add two numbers, Examples (#2)
cucumber examples/Calc/features/addition.feature:17 # Scenario Outline: Add two numbers, Examples (#3)
cucumber examples/Calc/features/division.feature:6 # Scenario: Regular numbers

4 scenarios (4 failed)
16 steps (16 undefined)
0m0.025s

## Expected Behavior
Expected behavior is to run  success.
## Current Behavior

Following and similar errors came:

  Scenario: Regular numbers                     # examples/Calc/features/division.feature:6
  no implicit conversion of nil into String (TypeError)
  ./features/support/hooks.rb:4:in `exists?'
  ./features/support/hooks.rb:4:in `Before'

## Steps to Reproduce (for bugs)
Just build the cucumber-cpp under ubuntu and you'll get the errors.

**Comment by muggenhor** [comment]
What's the version of cucumber that you're using? (`cucumber --version`)

I'm expecting this to be caused by a problem similar to #179. Which I'm reasonably sure is caused by a backwards compatible break in the wire protocol, similar to cucumber/cucumber-ruby#1183.

**Comment by ozenozkaya** [comment]
Hello, here below you'll see the version as 3.1.1:

dev@ubuntu:~/ws/cucumber-cpp$ cucumber --version
3.1.1

**Comment by konserw** [comment]
Hi @ozenozkaya please use cucumber 2.4

**Comment by sergey-bon** [comment]
@elominp 
@paoloambrosio 
> Not sure why we don't see the same issue in our CI build.

CI is set-up to use `cucumber 2.0.0` and this issue comes with `cucumber 2.1` or above.
https://github.com/cucumber/cucumber-cpp/blob/f79990879a3c2eea288de6efeefc4008937300cc/Gemfile#L4

**Comment by erichstuder** [comment]
> @elominp your problem seems to be unrelated to what has been reported in this issue.
> 
> The code that you pasted is related to the end-to-end test suite for Cucumber-CPP and not the Calc example. The environment variable `TMP_DIR` is passed by the build system whenever you run the `features`, `features-pretty` or `features-wip` targets.
> 
> It looks like running `cucumber examples\Calc` still tries to load the support code from `features\support\hooks.rb` instead of trying to reading from `examples\Calc\...`. Changing the current directory to `examples\Calc` before running `cucumber` should fix your problem. Not sure why we don't see the same issue in our CI build.

This solved my problem for now.
I would have saved a lot of time (about 2 days) if this hint was also present in the README.md
Maybe it would help to add it there.
